---
- name: All Device Configuration
  hosts: all

  vars_files:
  - creds/cred.yml

  tasks:
  - name: Load Configuration
    ansible.netcommon.cli_config:
      config: "{{ lookup('file', './device_configs/' + inventory_hostname + '.txt') }}"
...
